# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mgrsgrid.ui'
#
# Created: Wed Jul 22 20:07:21 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MgrsGrid(object):
    def setupUi(self, MgrsGrid):
        MgrsGrid.setObjectName(_fromUtf8("MgrsGrid"))
        MgrsGrid.setWindowModality(QtCore.Qt.ApplicationModal)
        MgrsGrid.resize(452, 319)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MgrsGrid.sizePolicy().hasHeightForWidth())
        MgrsGrid.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/mgrsgrid/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MgrsGrid.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(MgrsGrid)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_layer = QtGui.QHBoxLayout()
        self.horizontalLayout_layer.setObjectName(_fromUtf8("horizontalLayout_layer"))
        self.label = QtGui.QLabel(MgrsGrid)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_layer.addWidget(self.label)
        self.selected_layer = QtGui.QComboBox(MgrsGrid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selected_layer.sizePolicy().hasHeightForWidth())
        self.selected_layer.setSizePolicy(sizePolicy)
        self.selected_layer.setObjectName(_fromUtf8("selected_layer"))
        self.horizontalLayout_layer.addWidget(self.selected_layer)
        self.verticalLayout.addLayout(self.horizontalLayout_layer)
        self.horizontalLayout_precision = QtGui.QHBoxLayout()
        self.horizontalLayout_precision.setObjectName(_fromUtf8("horizontalLayout_precision"))
        self.precision_label = QtGui.QLabel(MgrsGrid)
        self.precision_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.precision_label.setObjectName(_fromUtf8("precision_label"))
        self.horizontalLayout_precision.addWidget(self.precision_label)
        self.precision = QtGui.QDoubleSpinBox(MgrsGrid)
        self.precision.setDecimals(0)
        self.precision.setMaximum(6.0)
        self.precision.setSingleStep(1.0)
        self.precision.setProperty("value", 3.0)
        self.precision.setObjectName(_fromUtf8("precision"))
        self.horizontalLayout_precision.addWidget(self.precision)
        self.verticalLayout.addLayout(self.horizontalLayout_precision)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.label_3 = QtGui.QLabel(MgrsGrid)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_9.addWidget(self.label_3)
        self.label_north = QtGui.QCheckBox(MgrsGrid)
        self.label_north.setChecked(True)
        self.label_north.setObjectName(_fromUtf8("label_north"))
        self.horizontalLayout_9.addWidget(self.label_north)
        self.label_south = QtGui.QCheckBox(MgrsGrid)
        self.label_south.setChecked(True)
        self.label_south.setObjectName(_fromUtf8("label_south"))
        self.horizontalLayout_9.addWidget(self.label_south)
        self.label_west = QtGui.QCheckBox(MgrsGrid)
        self.label_west.setChecked(True)
        self.label_west.setObjectName(_fromUtf8("label_west"))
        self.horizontalLayout_9.addWidget(self.label_west)
        self.label_east = QtGui.QCheckBox(MgrsGrid)
        self.label_east.setChecked(True)
        self.label_east.setObjectName(_fromUtf8("label_east"))
        self.horizontalLayout_9.addWidget(self.label_east)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_4 = QtGui.QLabel(MgrsGrid)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_8.addWidget(self.label_4)
        self.label_orientation = QtGui.QComboBox(MgrsGrid)
        self.label_orientation.setObjectName(_fromUtf8("label_orientation"))
        self.label_orientation.addItem(_fromUtf8(""))
        self.label_orientation.addItem(_fromUtf8(""))
        self.horizontalLayout_8.addWidget(self.label_orientation)
        self.font_button = QtGui.QPushButton(MgrsGrid)
        self.font_button.setObjectName(_fromUtf8("font_button"))
        self.horizontalLayout_8.addWidget(self.font_button)
        self.color_button = QtGui.QPushButton(MgrsGrid)
        self.color_button.setObjectName(_fromUtf8("color_button"))
        self.horizontalLayout_8.addWidget(self.color_button)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.grid_style_button = QtGui.QPushButton(MgrsGrid)
        self.grid_style_button.setObjectName(_fromUtf8("grid_style_button"))
        self.horizontalLayout_10.addWidget(self.grid_style_button)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.buttonBox = QtGui.QDialogButtonBox(MgrsGrid)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(MgrsGrid)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), MgrsGrid.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), MgrsGrid.reject)
        QtCore.QObject.connect(self.font_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MgrsGrid.chooseFont)
        QtCore.QObject.connect(self.color_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MgrsGrid.chooseColour)
        QtCore.QObject.connect(self.grid_style_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MgrsGrid.chooseStyle)
        QtCore.QObject.connect(self.selected_layer, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), MgrsGrid.changeLayer)
        QtCore.QMetaObject.connectSlotsByName(MgrsGrid)

    def retranslateUi(self, MgrsGrid):
        MgrsGrid.setWindowTitle(_translate("MgrsGrid", "Latitude / Longitude grid lines", None))
        self.label.setText(_translate("MgrsGrid", "Select existing layer:", None))
        self.selected_layer.setToolTip(_translate("MgrsGrid", "Select layer to use for extend of MGRS grid", None))
        self.precision_label.setText(_translate("MgrsGrid", "MGRS precision:", None))
        self.precision.setToolTip(_translate("MgrsGrid", "<html><head/><body><p>MGRS Precision</p></body></html>", None))
        self.label_3.setText(_translate("MgrsGrid", "Labels:", None))
        self.label_north.setToolTip(_translate("MgrsGrid", "Check this box to display north labels", None))
        self.label_north.setText(_translate("MgrsGrid", "North", None))
        self.label_south.setToolTip(_translate("MgrsGrid", "Check this box to display south  labels", None))
        self.label_south.setText(_translate("MgrsGrid", "South", None))
        self.label_west.setToolTip(_translate("MgrsGrid", "Check this box to display west labels", None))
        self.label_west.setText(_translate("MgrsGrid", "West", None))
        self.label_east.setToolTip(_translate("MgrsGrid", "Check this box to display east labels", None))
        self.label_east.setText(_translate("MgrsGrid", "East", None))
        self.label_4.setText(_translate("MgrsGrid", "Label orientation:", None))
        self.label_orientation.setToolTip(_translate("MgrsGrid", "<html><head/><body><p>Label orientation relatively to the frame</p></body></html>", None))
        self.label_orientation.setItemText(0, _translate("MgrsGrid", "Perpendicular", None))
        self.label_orientation.setItemText(1, _translate("MgrsGrid", "Parallel", None))
        self.font_button.setToolTip(_translate("MgrsGrid", "Select label font", None))
        self.font_button.setText(_translate("MgrsGrid", "Font...", None))
        self.color_button.setToolTip(_translate("MgrsGrid", "Select label color", None))
        self.color_button.setText(_translate("MgrsGrid", "Color...", None))
        self.grid_style_button.setToolTip(_translate("MgrsGrid", "Set grid lines style", None))
        self.grid_style_button.setText(_translate("MgrsGrid", "Set grid style...", None))

import resources_rc
